name: Training Pipeline (Daily)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-training-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train models
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python train.py

      - name: Upload trained models
        uses: actions/upload-artifact@v4
        with:
          name: trained-models-${{ github.run_number }}
          path: models/
          retention-days: 30